### PR TITLE
Add constraints to shifts

### PR DESCRIPTION
**Pull request by ncbui**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ x] Optimization
- [ ] Documentation Update

## Description of what PR does
Closes issue #37 
Adds validations on the Shifts model. An error will popup on the form if conditions are not met. All shifts must now have a role name, pay rate, start and end times. End times must happen after start times. 

## Related PRs (if any)
-
-

## QA Instructions, Screenshots, Recordings
Pull into your local env
Run 
```
bundle install
rails db:migrate
rails s
```
In browser, navigate to http://127.0.0.1:3000/shifts/

## Added tests?

- [ ] yes
- [ x ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help

## Added to documentation?

- [ ] Yes, project README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Alt-Text

### CODE REVIEW

**Review by GabrielleEaston — APPROVED** [review]
@ncbui Great job! Got the error message when tried to choose the wrong start/endtime!

**Comment by GabrielleEaston** [comment]
@ncbui @saradotlog @Timilehin08 I've noticed there is another issue with adding the pay amount. You can add a negative value. Should I create the issue for that? 🐼

**Comment by ncbui** [comment]
Great catch @GabrielleEaston! I can also add that to this PR if y'all don't mind. Rails has a validation helper, [numericality](https://guides.rubyonrails.org/active_record_validations.html#numericality), with an option to set values to be :greater_than_or_equal_to  X amount.

**Comment by ncbui** [comment]
Added a small update to PR to check that pay rate is equal to or greater than 0. Could you review again @GabrielleEaston ?

**Comment by GabrielleEaston** [comment]
@ncbui Thanks for adding this! ❤️

**Comment by GabrielleEaston** [comment]
@ncbui Reviewed it again! Got an error with negative pay as expected. 🥳 
It's still possible to put 0 as pay. I wonder if there's is a way to set to greater than 0 (not equal 0). 😁

**Comment by ncbui** [comment]
@GabrielleEaston it is possible to set pay greater than 0.

**Comment by ncbui** [comment]
Have updated the model. Please review when you have the chance

**Comment by saradotlog** [comment]
Hey @ncbui ! I reviewed this! Well done! 🎉  I got the error when I try to add a shift with the end time before the start time and when the pay rate is equal or less than 0.

One small thing... it still allows you to create a shift where the start and the end time are the same...  Shouldn't the end time be at least "an hour" or sometime after the start?

Another thing I noticed... It also allows you to create start and end times in the past... Wouldn't be better to check the start time is not before the current date/time?

**Comment by ncbui** [comment]
Good points Sara , These are also useful product rules that we can use to finetune the core product. All shifts must be at least as hour long. Users cannot create shifts in the past. I also think that shifts must start a certain amount of time after being created, to give workers time to travel. Have it currently set to an hour between creation and start time.

**Comment by ncbui** [comment]
I noticed that the pay rate is currently stored as an integer. Could add an issue to change this to a data type that can store cents?

**Comment by msarit** [comment]
Closing this PR in favor of V2 🙏🏾  (well done @ncbui !)

**Pull request closed without merging**
