### PR TITLE
Sara add description field to shifts table

### PR DESCRIPTION
**Pull request by saradotlog**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description of what PR does

Adds the description column to the shifts table.
It also adds the description fields to the shifts views and controller

## Related PRs (if any)
-
-

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help

## Added to documentation?

- [ ] Yes, project README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Alt-Text

### CODE REVIEW

**Comment by saradotlog** [comment]
Hey @aritamana @GabrielleEaston @ncbui @Timilehin08 !

I added the description field to the shifts table and to the views/controller.

I tried to create, destroy, edit and view the shifts and it seems to work properly, but if I missed something please let me know. 

One thing I realised is that the "notice" alert at the top ("Shift was successfully created.", "Shift was successfully updated"... ) appears twice. Should I remove it from the shifts views? It is already in `app/views/layouts/application.html.erb`, I remember I had to add it there for the user auth when installing devise.

**Comment by GabrielleEaston** [comment]
@saradotlog Great idea to remove it!

**Comment by ncbui** [comment]
@saradotlog I agree with removing the duplicate. 
Have pulled this into my local env. Am able to successfully add, edit, and view the new description field. Good work Sara!

**Review by ncbui — APPROVED** [review]

**Comment by Timilehin08** [comment]
Welldone @saradotlog. I also think it will be good to remove the duplicate.

**Review by Timilehin08 — APPROVED** [review]

**Comment by GabrielleEaston** [comment]
Yes, the new issue is the way to go! Thank you @saradotlog

**Review by GabrielleEaston — APPROVED** [review]
Pulled it to my local. Got the description field. Created, edited, deleted the shifts with it. Works fine for me!!! Thanks @saradotlog

**Pull request merged**
