### PR TITLE
Create org table

### PR DESCRIPTION
**Pull request by ncbui**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description of what PR does
Adds an organization model, controller, and view for Org name and address.
The view contains a form that has light validation (fields cannot be empty for the most basic version of this form).

Note: I have created new issues to add associations to User table #46 and further testing #45 . This does not include the photo field we discussed in wireframe meetings. 

## Related PRs (if any)
-
-

## QA Instructions, Screenshots, Recordings

To QA:
> pull repo into your local env
> migrate database with `rails db:migrate`
> start server with `rails server`
> navigate to http://127.0.0.1:3000/organizations/
> to run test (there are none at the moment), run `rails db:migrate RAILS_ENV=test`, then`rails test test/models/organization_test.rb`

## Added tests?

- [ ] yes
- [ x] no, because they aren't needed for this PR. Have added issue to work on them #45 
- [ ] no, because I need help. 

## Added to documentation?

- [ ] Yes, project README
- [ x ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Alt-Text

### CODE REVIEW

**Review by Timilehin08 — APPROVED** [review]

**Comment by saradotlog** [comment]
Hi @ncbui !!
I pulled your code in my local.
I ran into an error running db:migrate

`PG::DuplicateColumn: ERROR:  column "org_description" of relation "organizations" already exists`

I see that there are two migrations to add the description to the organisations (`db/migrate/20210329214712_add_description_to_organizations.rb` and `db/migrate/20210329220820_add_org_description_to_organizations.rb`)
could be that the problem?

**Comment by GabrielleEaston** [comment]
Hey, @saradotlog @ncbui @Timilehin08 I ran into the same error as Sara. After googling, I found a tip to run rails db:reset.  I did that and after that, I was able to run the migrations and start the server. 
Here is the link https://stackoverflow.com/questions/13333580/duplicate-column-name-error-when-running-migration

**Comment by GabrielleEaston** [comment]
Btw I love the QA instructions! @ncbui

**Comment by saradotlog** [comment]
Hi! yes, but rails db:reset wouldn't drop the database? Now might be fine but I was wondering, what would happen if we have data we can't remove? Maybe would be better to delete the duplicated migration? I am just thinking out loud, don't know if that's possible

**Comment by GabrielleEaston** [comment]
Rails db:reset does the following>> rails db:drop , rails db:create, rails db:migrate
I have no idea if it's safe and good practice to use it.  I am sure it's possible to delete the duplicated migration as well.

**Comment by GabrielleEaston** [comment]
https://stackoverflow.com/questions/40632232/delete-migration-file-with-duplicate-migration-name

**Comment by saradotlog** [comment]
Yeah, it is what I read, that it drops the db. Probably not a big problem in our locals, but I just was wondering what would be the good practice.

**Comment by GabrielleEaston** [comment]
@saradotlog You are making a very good point! I didn't think about the production and when it's live. I'm glad you brought it up.

**Comment by saradotlog** [comment]
I still have the same problem... I guess i will have to drop the database. 
Even if there is only one file now, I don't know if it can be because I already tried to ran it the last time and I already have the field? :confounded:

**Review by msarit — APPROVED** [review]
Looks good, Cam! 🚀 
I think we should create an issue that will allow organizations to create shifts? 👀 😄

**Review by saradotlog — APPROVED** [review]

**Comment by ncbui** [comment]
Thanks for reviewing this everyone. @msarit  good idea, I'll wite an issue to allow orgs to create shifts

**Pull request merged**
