### PR TITLE
Update readme with Cam's personal info

### PR DESCRIPTION
**Pull request by ncbui**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description of what PR does
Updated README.md with Cam's personal info

## Related PRs (if any)
- NA
-

## Added tests?

- [ ] yes
- [x] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help

## Added to documentation?

- [x] Yes, project README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Alt-Text

### CODE REVIEW

**Review by Timilehin08 — COMMENTED** [review]
Looks good!

**Review by GabrielleEaston — APPROVED** [review]
Looks great, @ncbui

**Comment by msarit** [comment]
@ncbui Hey Cam! Please resolve conflicts on your branch and push up again. Then we'll get your PR merged 😄

**Comment by ncbui** [comment]
@msarit Hi Arit! Conflicts resolved.

**Review by msarit — APPROVED** [review]
Awesome work!

**Comment by ncbui** [comment]
Thank you!

**Pull request merged**
